on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files to server test 1
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: s0.serv00.com
        port: 21
        username: f11818_miavaka
        password: 1027Miavaka
        server-dir: ./domains/usertest.serv00.net/public_html/simulation_eolienne/
        local-dir: ./
        
    - name: 📂 Sync files to server Nofidiana 
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp-nofidiana.alwaysdata.net
        port: 21
        username: nofidiana
        password: 1027Miavaka
        server-dir: ./www/simulation_eolienne/
        local-dir: ./
